### PR TITLE
add devision-by-zero check

### PR DESCRIPTION
**Pull request by Vasiliy566**
add zero-division check

### CODE REVIEW

**Comment by Vasiliy566** [comment]
closes https://github.com/RaduG/pytest_func_cov/issues/10

**Review by RaduG — CHANGES_REQUESTED** [review]
Could you please change the if to `if total_funcs != 0`? Easier to read

**Comment by RaduG** [comment]
Also thanks a lot for your submission, sorry for the delay I must've missed the notification

**Comment by Vasiliy566** [comment]
changed as you requested
tty for fast answer

**Comment by Vasiliy566** [comment]
@RaduG

**Review by RaduG — APPROVED** [review]
Great stuff, thanks!

**Pull request merged**
